//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PALADIN2.db_context
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int productID { get; set; }
        public string productName { get; set; }
        public int price { get; set; }
        public string description { get; set; }
    }
}
