//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIABLO.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public int Role_ID { get; set; }
        public string Role_Name { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
